# Generated by Django 5.0.3 on 2024-03-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-id',)},
        ),
    ]
