# Generated by Django 5.0.3 on 2024-03-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='subject',
        ),
    ]
